version: "3.7"

networks:
  loki:

services:   
  loki:
    image: grafana/loki:2.4.1
    # image: grafana/loki:master
    ports:
      - "3101:3100"
    volumes:
      - "C:/Users/saksh/SakshiOneDrive/OneDrive/SakshiOnedrive/Projects/20220101_Logging_Module_with_Docker/grafana-loki/dump/loki-config.yaml:/etc/loki/local-config.yaml"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - "C:/Users/saksh/SakshiOneDrive/OneDrive/SakshiOnedrive/Projects/20220101_Logging_Module_with_Docker/grafana-loki/dump/promtail-config.yaml:/etc/promtail/config.yml"
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki


