version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.6.1
    volumes:
      - C:/Users/saksh/SakshiOneDrive/OneDrive/SakshiOnedrive/Projects/20220101_Logging_Module_with_Docker/grafana-loki/loki/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    # restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - C:/Users/saksh/SakshiOneDrive/OneDrive/SakshiOnedrive/Projects/20220101_Logging_Module_with_Docker/grafana-loki:/var/log
      - C:/Users/saksh/SakshiOneDrive/OneDrive/SakshiOnedrive/Projects/20220101_Logging_Module_with_Docker/grafana-loki/promtail/promtail-config.yaml:/etc/promtail/config.yml
    # restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    # volumes:
    #   - C:/Users/saksh/SakshiOneDrive/OneDrive/SakshiOnedrive/Projects/20220101_Logging_Module_with_Docker/grafana-loki/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    # restart: unless-stopped
    networks:
      - loki
